### ISSUE TITLE
Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by MuhammadZubair472** [NoriSte/npm-run-programmatically-example#2]
I run this command 
**npm install --save-dev npm**

then use this code snippets 
----------
npm.load();
--------------
npm.load(() => npm.run("test")); 

I found this error:

Uncaught TypeError: Cannot read property 'filename' of undefined

**Comment by NoriSte** [comment]
HI @MuhammadZubair472 , could you share a repository to play with, please?

**Comment by MuhammadZubair472** [comment]
Hi @NoriSte , thank you for replay, I am working in a private project, but this is my package.json file

```
{
    "name": "app_name",
    "version": "1.0.0",
    "main": "main.js",
    "devDependencies": {
        "electron": "^8.0.0",
        "electron-builder": "^22.3.2",
        "electron-packager": "^14.2.1"
    },
    "scripts": {
        "start": "electron .",
        "startServer": "nodemon index.js",
        "build": "electron-packager .",
        "test": "echo \"Error: no test specified\"",
        "dist": "electron-builder",
        "dev": "npm run start",
        "all": "npm-run-all --parallel startServer start"
    },
    "build": {
        "appId": "com.myapp.app",
        "productName": "myapp",
        "target": "NSIS",
        "directories": {
            "output": "build"
        },
        "nsis": {
            "allowToChangeInstallationDirectory": true,
            "oneClick": false
        }
    },
    "dependencies": {
        "D": "^1.0.0",
        "body-parser": "^1.19.0",
        "express": "^4.17.1",
        "http": "0.0.0",
        "https": "^1.0.0",
        "mysql": "^2.18.1",
        "npm-run-all": "^4.1.5"
    }
}
```

**Comment by NoriSte** [comment]
Hi @MuhammadZubair472 
Please share with me at least
- where the file containing `npm.load(() => npm.run("test"));` is located (is the `index.js` file launched with nodemon?
- how you launch it
Thank you 
Best
Stefano

**Comment by MuhammadZubair472** [comment]
Hi @NoriSte 

Oh, I got it, infect I was looking to run it for my reactjs, not by nodemon [or node.js api].
It is working fine with nodemon index.js, thank you for your response.

**Comment by NoriSte** [comment]
Isolating an issue let you find the solution 90% of the times 😉
You're welcome!!
Stefano
